### ISSUE TITLE
Crash on level change, possibly related to multiple leashed pets

### ISSUE THREAD

**Issue by dvr333** [tung/DynaHack#93]
I got a crash in Dynahack 0.5.4 upon changing from DL7 to DL8 as a Tou-Hum-Mal-Neu while having two cats adjacent to me (large cat at west, kitten at north), both of whom were leashed (unsure of leash beatitude, probably both uncursed). The crash occurred immediately after I hit '>' to go down the stairs.

Save file on [Dropbox](https://dl.dropboxusercontent.com/u/12241609/1389426594_Eight%20Rising%20Moon.nhgame)

**Comment by tung** [comment]
I found the problem, and it actually has nothing to do with your leashed pets. The crash happens when you enter the Oracle level: the statues there typically have contents, which are supposed to have a pointer back to the level they're on which 0.5.4's timer/light source fix needs, but NitroHack (what DynaHack is based on) never sets that back pointer properly, hence crash.

The fix for this will come with 0.5.5, which I'll put out soon so you can keep playing your character.

**Comment by tung** [comment]
Fixed by 56d2eefb525a517cd047a3569963a0cc17477d90.

**Comment by tung** [comment]
@dvr333 I just put out DynaHack 0.5.5 which should let you just pick up where you left off.
